[package]
name = "steamgear"
version = "0.1.0"
edition = "2021"

[dependencies.dashmap]
version = "5.5.3"

[dependencies.futures]
version = "0.3.30"

[dependencies.steamgear-sys]
path = "./steamgear-sys"

[dependencies.parking_lot]
version = "0.12.3"
